# Generated by Django 5.0.1 on 2024-01-04 21:41

import django.db.models.deletion
import song.tools
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="create date"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="modify date"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "image",
                    models.ImageField(
                        default="artist/default.jpg",
                        upload_to=song.tools.UploadToPathAndRename("artist"),
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="song/default.jpg",
                        upload_to=song.tools.UploadToPathAndRename("song"),
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("audio", models.FileField(blank=True, null=True, upload_to="")),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("count_view", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_data", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relate_song",
                        to="song.artist",
                    ),
                ),
                ("category", models.ManyToManyField(to="song.category")),
            ],
            options={
                "ordering": ("created_date",),
            },
        ),
    ]
