# Generated by Django 5.0.1 on 2024-01-05 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("song", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="artist",
            old_name="title",
            new_name="name",
        ),
        migrations.AddField(
            model_name="song",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="song_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
