# Generated by Django 4.2.3 on 2024-01-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_lyric'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
