# Generated by Django 4.2.3 on 2024-01-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_artist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='song.category'),
        ),
    ]
