# Generated by Django 4.2.3 on 2024-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_remove_song_slug_alter_song_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='category',
            field=models.ManyToManyField(to='song.category'),
        ),
    ]
